//-----------------------------------------------------------------------------
// Copyright (c) 2024 Electronic Arts. All rights reserved.
//-----------------------------------------------------------------------------

//!include particle.inc
//!include simConstants.inc
//!include matrix.inc
//!include rigidbody.inc

// Code-generated by UniformBufferFactory
//!insert RenderConstants

// const values like RenderModeStandard etc
// that are plugged in from js
//!insert RenderEnums

@group(0) @binding(0) var<uniform> g_constants : RenderConstants;
@group(0) @binding(1) var<storage> g_particles : array<Particle>;
@group(0) @binding(2) var<storage> g_rigidBodies : RigidBody;


struct VertexOutput {
  @builtin(position) clipPosition : vec4f,
  @location(0) particlePosition : vec2f,
  @location(1) vertexPosition : vec2f,
  @location(2) particleColor : vec3f,
  @location(3) particleRadius : f32,
    @location(4) worldPosition : vec2f, // For debug view
};

const s_quadVertices = array(
  vec2f(-1.0, -1.0), vec2f(1.0, -1.0), vec2f(1.0, 1.0),
  vec2f(-1.0, -1.0), vec2f(1.0, 1.0),  vec2f(-1.0, 1.0)
);

// We now have two vertex shaders: one for particles, one for the debug view.
// We select which one to run based on the render mode.

@vertex
fn vertexMain(@builtin(vertex_index) vertexId: u32, @builtin(instance_index) instanceId : u32) -> VertexOutput {
    // If we are in debug mode, run the full-screen vertex shader
    if (g_constants.renderMode == f32(RenderModeRigidBody)) {
        let clipPos = vec4f(s_quadVertices[vertexId], 0.0, 1.0);

        // Convert clip space [-1, 1] to UV space [0, 1]
        let uv = clipPos.xy * 0.5 + 0.5;

        // Convert UV space to world space
        // This is the inverse of the transform used to project particles.
        let worldPos = (uv * 2.0 - 1.0) * g_constants.viewExtent + g_constants.viewPos;
        
        // Flip Y-axis to match simulation coordinates (Y-up)
        // This depends on your coordinate system setup, adjust if needed.
        // worldPos.y = g_constants.canvasSize.y / (g_constants.canvasSize.x / g_constants.gridSize.x) - worldPos.y;

        return VertexOutput(clipPos, vec2f(0.0), vec2f(0.0), vec3f(0.0), 0.0, worldPos);
    }
    
    // --- Original particle rendering vertex shader logic ---
  let onePixel = 1.0 / f32(g_constants.canvasSize.x);
  let particle = g_particles[instanceId];
  if(particle.enabled == 0) {
    return VertexOutput(vec4f(0.0), vec2f(0.0), vec2f(0.0), vec3f(0.0), 0.0, vec2f(0.0));
  }
  var particlePosition : vec2f = particle.position;
  var particleMaterialRadius = g_constants.particleRadiusTimestamp.x * sqrt(particle.volume);
  var quadVertexPosition = s_quadVertices[vertexId] * (1.0 + 500.0 * onePixel) * particleMaterialRadius;
  var vertexPosition = quadVertexPosition + particlePosition;
  var vertexPositionInRenderSpace = (vertexPosition - g_constants.viewPos) / g_constants.viewExtent;
  var color = particle.color;
  if(g_constants.renderMode == f32(RenderModeCompression)) {
    let density = particle.liquidDensity;
    color = vec3f(-5.0*log(density), 5.0*log(density), color.z);
  } else if(g_constants.renderMode == f32(RenderModeVelocity)) {
    color = vec3f((particle.displacement*g_constants.deltaTime*1000.0 + 0.5f), color.z);
  }
  return VertexOutput(
    vec4f(vertexPositionInRenderSpace, 0.0, 1.0),
    particlePosition,
    vertexPosition,
    color,
    particleMaterialRadius,
        vec2f(0.0) // worldPosition not used for particles
  );
}

@fragment
fn fragmentMain(input: VertexOutput) -> @location(0) vec4f {
    // --- New Debug Logic ---
    if (g_constants.renderMode == f32(RenderModeRigidBody)) {
        let query_pos = input.worldPosition;
        var collided = false;

        // Loop through all bodies and their shapes
        for (var bodyIndex = 0u; bodyIndex < g_rigidBodies.body_count; bodyIndex = bodyIndex + 1u) {
            let body = g_rigidBodies.bodies[bodyIndex];
            for (var i = 0.0; i < body.shapeCount; i = i + 1.0) {
                let shapeIndex = u32(body.shapeStartIndex + i);
                let localShape = g_rigidBodies.shapes[shapeIndex];

                // Call our collision function for the current pixel's world position
                let collideResult = RBcollide(localShape, body.position, body.angle, query_pos);

                if (collideResult.collides) {
                    collided = true;
                    break; // Exit inner loop
                }
            }
            if (collided) {
                break; // Exit outer loop
            }
        }

        if (collided) {
            return vec4f(1.0, 0.2, 0.2, 0.7); // Draw semi-transparent red for collided pixels
        } else {
            discard; // Don't draw anything for non-colliding pixels
        }
    }

    // --- Original Particle Fragment Logic ---
  let onePixel = 1.0 / f32(g_constants.canvasSize.x);
  let particleRadius = input.particleRadius;
  let fragOffsetFromCenter = input.vertexPosition - input.particlePosition;
  let distanceFromCenter = length(fragOffsetFromCenter);
  let alpha = smoothstep(0.0, 1.0, 1.0-(distanceFromCenter-particleRadius)/(onePixel*500.0*particleRadius) );
  return vec4f(input.particleColor, alpha);
}